FTPOSError: removed any uses of the attribute ftp_exception. Because     FTPOSError wraps ftplib errors and we have an exception hierarchy,     there should no longer be a need to access the ftplib exception.
--HG--
extra : convert_revision : svn%3A778c30c8-61e0-0310-89d4-fe2f97a467b2/trunk%4051